id: 66f922edb24a4d6bbcb4b644b4f9ee64
initial_creation_type: ocr
source_metadata:
  volumes:
    251cd9ca3da44632b382a586889f3e15:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: དཔལ་གསང་བ་འདུས་པའི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1634
      volume_number: 18
